# Generated by Django 3.2.7 on 2021-10-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='do_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Reserved'), (3, 'SOLD - not available anymore')], default=1),
        ),
    ]
