# Generated by Django 3.2.7 on 2021-10-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sale_price',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
