# Generated by Django 3.2.7 on 2021-10-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0004_alter_car_sale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name_plural': 'Models'},
        ),
    ]
