# Generated by Django 3.2.7 on 2021-10-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecar',
            old_name='service_price',
            new_name='annual_service_price',
        ),
        migrations.AddField(
            model_name='servicecar',
            name='minor_service_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=6, null=True),
        ),
    ]
