# Generated by Django 3.2.7 on 2021-10-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Completed'), (2, 'In Progress'), (3, 'Not Started')], default=3),
        ),
    ]
